FROM mysql:latest

# Environment variables for MySQL configuration
ENV MYSQL_ROOT_PASSWORD=1234 \
    MYSQL_DATABASE=app_db \
    MYSQL_USER=app_user \
    MYSQL_PASSWORD=1234

# Exposer port 3306 for MySQL connections
EXPOSE 3306

# Set the data directory as a volume
VOLUME /var/lib/mysql

# Copy SQL initialization script to set up the database and user
COPY init.sql /docker-entrypoint-initdb.d/в
